import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import { Rubik_Mono_One } from "next/font/google";
import { Montserrat } from "next/font/google";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserratAlt = Montserrat_Alternates({
  subsets: ["latin", "cyrillic"],          // ✅ додали кирилицю
  weight: ["400", "500", "600", "700"],    // ✅ нормальні ваги
  variable: "--font-montserrat-alt",
  display: "swap",
});

const rubikMonoOne = Rubik_Mono_One({
  subsets: ["latin", "cyrillic"],  // кирилиця, якщо потрібна
  weight: "400",                   // Rubik Mono One підтримує тільки 400
  variable: "--font-rubik-mono-one",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],  // кирилиця для української
  weight: ["400", "500", "600", "700"],  // потрібні ваги
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="uk" className={`${montserratAlt.variable} ${geistMono.variable} ${geistSans.variable} ${rubikMonoOne.variable} ${montserrat.variable}`}>
      {/* Можеш лишити body без montserratAlt.className — ми керуємо шрифтом через CSS-змінну */}
      <body className="antialiased">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
